config/routes.rb
Prose1::Application.routes.draw do
  root :controller => :home, :action => :index
  devise_for :users
  resources :poetries

  resources :pieces

  resources :songs

  resources :authors

  resources :likes

  resources :comments

  resources :proses

  resources :users
  resources :home
  get '/test/wechat', to: 'wechat_supports#auth_wechat'

end

app/models/poetry.rb
#诗词
class Poetry < ActiveRecord::Base
  include SoftDelete
  validates_presence_of :title, message: 'title is must!'
  validates_presence_of :content, :message => 'content is must!'
  validates_presence_of :author, :message => 'author is must!'
  validates_length_of :title, :maximum => 50, :message => 'Up to 50 characters'
  validates_length_of :author, :maximum => 10, :message => 'Up to 10 characters'
  belongs_to :user
  belongs_to :author_class, :class_name => 'Author', :foreign_key => 'author_id'
  has_many :comments, -> { where(genre: 1) }, foreign_key: :outer_id
  attr_accessible :title, :content, :author, :author_id, :user_id, :last_comment_id, :commented_at, :comments_count, :likes_count,
                  :comment_user_ids, :last_commented_user_name, :who_deleted, :excellent, :deleted_at, :updated_by

  before_save :update_author

  def can_edit?(user)
    return false if user.blank?
    self.user_id==user.id or user.is_admin?
  end

  def can_delete?(user)
    return false if user.blank?
    user.is_admin?
  end

  private
  def update_author
    return if self.author.blank?
    _author = Author.where(name: self.author).first
    _author = Author.create(:name => self.author) if _author.blank?
    self.author_id=_author.id
  end
end

app/controllers/poetries_controller.rb
class PoetriesController < ApplicationController
  before_filter :set_poetry, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:index, :show]

  respond_to :html

  def index
    @poetries = Poetry.paginate(:per_page => 10, :page => params[:page]||1).order(id: :desc)
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(outer_id: @poetry.id, genre: 1).includes(:user).order(id: :desc)
  end

  def new
    @poetry = Poetry.new
  end

  def edit
  end

  def create
    @poetry = Poetry.new(params[:poetry].merge(:user_id => current_user.id))
    @poetry.save
    respond_with(@poetry)
  end

  def update
    @poetry.update_attributes(params[:poetry].merge(:updated_by => current_user.id))
    respond_with(@poetry)
  end

  def destroy
    @poetry.destroy
    @poetry
    respond_with(@poetry)
  end

  private
  def set_poetry
    @poetry = Poetry.find(params[:id])
  end
end

app/helpers/poetries_helper.rb
module PoetriesHelper
end

app/views/poetries/_form.html.erb
<%= form_for(@poetry) do |f| %>
    <% if @poetry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@poetry.errors.count, "error") %> prohibited this poetry from being saved:</h2>

          <ul>
            <% @poetry.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label '标题' %>：
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label '作者' %>：
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label '内容' %>
      <br>
      <%= f.text_area :content, :size => '87x15' %>
    </div>
    <% if current_user.is_admin? %>
        <div class="field">
          <%= f.label '精华' %>：
          <%= f.select :excellent, [['否', 0], ['是', 1]], {} %>
        </div>
    <% end %>
    <div class="actions">
      <%= f.submit '确定' %>
    </div>
<% end %>

app/views/poetries/edit.html.erb
<h1>编辑诗词</h1>

<%= render 'form' %>

<%= link_to '查看', @poetry %> |
<%= link_to '返回', poetries_path %>

app/views/poetries/index.html.erb
<p class="publish clearfix"><%= link_to '赋诗一首', new_poetry_path %></p>
<% @poetries.each do |song| %>
    <%= render :partial => 'layouts/list_item', :locals => {:item => song} -%>
<% end %>
<div class="panel-footer clearfix">
  <%= will_paginate @poetries %>
  共 <%= @poetries.total_entries %> 条
</div>

app/views/poetries/new.html.erb
<h1>新建诗词</h1>

<%= render 'form' %>

<%= link_to '返回', poetries_path %>

app/views/poetries/show.html.erb
<%= render :partial => 'layouts/sidebar', :locals => {:author => @poetry.author_class} -%>
<div class="detail">
  <p id="notice"><%= notice %></p>

  <p class="title">
    <%= @poetry.title %>
  </p>

  <p class="source">
    由
    <%= @poetry.user.try(:name) -%>
    于
    <%= @poetry.created_at.strftime('%Y-%m-%d %H:%M:%S') -%>
    发布
  </p>

  <p>
    <%= @poetry.content %>
  </p>

  <%= link_to '编辑', edit_poetry_path(@poetry) if @poetry.can_edit?(current_user) %> |
  <%= link_to '返回', poetries_path %>
</div>
<%= render :partial => 'layouts/comments', :locals => {:subject => @poetry, :genre => 1} -%>