config/routes.rb
Prose1::Application.routes.draw do
  root :controller => :home, :action => :index
  devise_for :users
  resources :poetries

  resources :pieces

  resources :songs

  resources :authors

  resources :likes

  resources :comments

  resources :proses

  resources :users
  resources :home
  get '/test/wechat', to: 'wechat_supports#auth_wechat'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @songs = Song.where(excellent: 1).limit(5)
    @pieces = Piece.where(excellent: 1).limit(5)
    @poetries = Poetry.where(excellent: 1).limit(5)
    @proses = Prose.where(excellent: 1).limit(5)
  end
end

app/views/home/index.html.erb
<div class="section">
  <div class="top">诗词
    <span style="float: right;font-size:12px;font-weight: normal;">
      <%= link_to '更多...', poetries_path -%>
    </span>
  </div>
  <div class="middle">
    <% @poetries.each_with_index do |song, i| %>
        <%= render :partial => 'layouts/item', :locals => {:item => song, :is_last => @poetries.size==i+1} -%>
    <% end %>
  </div>
</div>
<div class="section">
  <div class="top">美文
      <span style="float: right;font-size:12px;font-weight: normal;">
      <%= link_to '更多...', proses_path -%>
    </span>
  </div>
  <div class="middle">
    <% @proses.each_with_index do |song, i| %>
        <%= render :partial => 'layouts/item', :locals => {:item => song, :is_last => @proses.size==i+1} -%>
    <% end %>
  </div>
</div>
<div class="section">
  <div class="top">杂谈
      <span style="float: right;font-size:12px;font-weight: normal;">
      <%= link_to '更多...', pieces_path -%>
    </span>
  </div>
  <div class="middle">
    <% @pieces.each_with_index do |song, i| %>
        <%= render :partial => 'layouts/item', :locals => {:item => song, :is_last => @pieces.size==i+1} -%>
    <% end %>
  </div>
</div>
<div class="section">
  <div class="top">歌曲
      <span style="float: right;font-size:12px;font-weight: normal;">
      <%= link_to '更多...', songs_path -%>
    </span>
  </div>
  <div class="middle">
    <% @songs.each_with_index do |song, i| %>
        <%= render :partial => 'layouts/item', :locals => {:item => song, :is_last => @songs.size==i+1} -%>
    <% end %>
  </div>
</div>