config/routes.rb
Prose1::Application.routes.draw do
  root :controller => :home, :action => :index
  devise_for :users
  resources :poetries

  resources :pieces

  resources :songs

  resources :authors

  resources :likes

  resources :comments

  resources :proses

  resources :users
  resources :home
  get '/test/wechat', to: 'wechat_supports#auth_wechat'

end

app/views/layouts/_comment.erb
<div class="comment">
  <p class="comment-top">
    <%= comment.created_at.strftime('%Y-%m-%d %H:%M:%S') -%>
    <%= comment.user.try(:name) -%>
    说：
  </p>

  <p>
    <%= comment.content -%>
  </p>
</div>

app/views/layouts/_comments.erb
<div class="show_comment">
  <div class="clearfix">
    <div class="like">
      <a href="/likes/<%= subject.id -%>/edit?genre=<%= genre -%>">
        <i class="fan"></i>
        喜欢
      </a>
      <span class="likes-count"><%= subject.likes_count -%></span>
    </div>
  </div>
  <div class="comments">
    <p class="count">
      共收到 <%= @comments.count -%> 条评论
    </p>
    <% @comments.each do |comment| %>
        <%= render :partial => 'layouts/comment', :locals => {:comment => comment} -%>
    <% end %>
  </div>
  <% if current_user %>
      <div class="comment_form">
        <%= form_for(@comment) do |f| %>
            <% if flash[:comment_notice].present? %>
                <div id="error_explanation">
                  <%= flash[:comment_notice] -%>
                </div>
            <% end %>
            <%= hidden_field_tag 'comment[genre]', genre -%>
            <%= hidden_field_tag 'comment[outer_id]', subject.id -%>
            <div class="field">
              <%= f.label '说点什么' %>
              <br>
              <%= f.text_area :content, :size => '67x5' %>
            </div>
            <div class="actions">
              <%= f.submit '发表' %>
            </div>
        <% end %>
      </div>
  <% else %>
      <%= render :partial => 'layouts/unlogin' -%>
  <% end %>
</div>

app/views/layouts/_footer.erb
<div id="footer">
  他身家千万，拥有豪车无数，私家豪华餐厅，现代化农牧场。自从QQ号丢了以后，他就一无所有了。
  <br/>
  初中英语水平支撑到现在。真有点力不从心啊。。。
</div>

app/views/layouts/_header.erb
<div id="header">
  <h2>
    诗词歌赋
    <span style="float: right;font-size:15px;font-weight: normal;">
          <% if current_user %>
      欢迎您！
          <%= current_user.name -%>
          &nbsp;
          <%= link_to '退出', destroy_user_session_path, :method => :delete -%>
              <% else %>
<%= link_to '登陆', new_session_path(User.new) %>
          &nbsp;
          <%= link_to "注册", new_registration_path(User.new) %>
      <% end %>
    </span>
  </h2>
</div>

app/views/layouts/_item.erb
<div class="item <%= is_last ? 'item_last' : '' -%>">
  <div class="left">

  </div>
  <div class="right">
    <p class="title"><%= link_to item.title, item -%></p>

    <p class="description"><%= item.content.to_s.truncate(67) -%></p>

    <p class="bottom">
      由
      <%= item.user.try :name -%>
      于
      <%= item.created_at.strftime('%Y-%m-%d %H:%M:%S') -%>
      发布；
      收到
      <%= link_to item.comments_count.to_i, item -%>
      条评论，
      <%= link_to item.likes_count.to_i, item -%>
      条喜欢。
      &nbsp;&nbsp;
      作者：<%= link_to item.author, item.author_class -%>
    </p>
  </div>
</div>

app/views/layouts/_list_item.erb
<div class="item">
  <div class="left">

  </div>
  <div class="right">
    <p class="title"><%= link_to item.title, item -%></p>

    <p class="description">
      <%= item.content.to_s.truncate(107) -%>
    </p>

    <p class="bottom">
      由
      <%= item.user.try :name -%>
      于
      <%= item.created_at.strftime('%Y-%m-%d %H:%M:%S') -%>
      发布；
      收到
      <%= link_to item.comments_count.to_i, item -%>
      条评论，
      <%= link_to item.likes_count.to_i, item -%>
      条喜欢。
      &nbsp;&nbsp;
      作者：<%= link_to item.author, item.author_class -%>
      <span style="float: right;">
              <% if item.class==Poetry %>
          <%= link_to '编辑', edit_poetry_path(item) if item.can_edit?(current_user) %>
      <% elsif item.class==Prose  %>
          <%= link_to '编辑', edit_prose_path(item) if item.can_edit?(current_user) %>
      <% elsif item.class==Piece  %>
          <%= link_to '编辑', edit_piece_path(item) if item.can_edit?(current_user) %>
      <% elsif item.class==Song  %>
          <%= link_to '编辑', edit_song_path(item) if item.can_edit?(current_user) %>
      <% end %>
        &nbsp;
        <%= link_to '删除', item, method: :delete, data: {confirm: 'Are you sure?'} if item.can_delete?(current_user) %>
      </span>
    </p>
  </div>
</div>

app/views/layouts/_sidebar.erb
<div class="sidebar">
  <p>
    <%= image_tag(image_path("liu#{rand(3)}.jpg"), :width => '80px', :height => '100px', :style => 'float:right;') -%>
    作者：<%= link_to author.name, author -%>
    <br>
    <% if author.birthday.present? %>
        <%= author.birthday -%>
        <br>
    <% end %>
    <% if author.birthday.present? %>
        <%= author.dynasty -%>
        <br>
    <% end %>
    <%= author.description -%>
  </p>
</div>

app/views/layouts/_top.erb
<ul>
  <li class="<%= controller_name=='home' ? 'select' : '' -%>"><%= link_to '首页', '/home' -%></li>
  <li class="<%= controller_name=='poetries' ? 'select' : '' -%>"><%= link_to '诗词', '/poetries' -%></li>
  <li class="<%= controller_name=='proses' ? 'select' : '' -%>"><%= link_to '美文', '/proses' -%></li>
  <li class="<%= controller_name=='pieces' ? 'select' : '' -%>"><%= link_to '杂谈', '/pieces' -%></li>
  <li class="<%= controller_name=='songs' ? 'select' : '' -%>"><%= link_to '歌曲', '/songs' -%></li>
  <li class="<%= controller_name=='authors' ? 'select' : '' -%>"><%= link_to '作者', '/authors' -%></li>
  <% if current_user and current_user.is_admin? %>
      <li class="<%= controller_name=='users' ? 'select' : '' -%>"><%= link_to '用户', '/users' -%></li>
  <% end %>
</ul>

app/views/layouts/_unlogin.erb
<p class="unlogin">
  <%= link_to '登陆', new_session_path(User.new) %>
  后可评论, 如果你还没有账号你可以
  <%= link_to "注册", new_registration_path(User.new) %>
  一个帐号。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>赋美</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" type="text/css" href="/simditor/styles/font-awesome.css"/>
  <link rel="stylesheet" type="text/css" href="/simditor/styles/simditor.css"/>
  <script type="text/javascript" src="/simditor/scripts/js/jquery.min.js"></script>
  <script type="text/javascript" src="/simditor/scripts/js/module.js"></script>
  <script type="text/javascript" src="/simditor/scripts/js/uploader.js"></script>
  <script type="text/javascript" src="/simditor/scripts/js/simditor.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%= render :partial => 'layouts/header' -%>
  <p id="notice"><%= notice %></p>

  <p id="alert"><%= alert %></p>

  <div class="inner wrap clearfix">
    <div class="inner_top"><%= render :partial => 'layouts/top' -%></div>
    <div class="content clearfix"><%= yield %></div>
  </div>
  <%= render :partial => 'layouts/footer' -%>
</div>
</body>
</html>